---

## You must fill the empty variables

# Common

base_domain:
tor_hostname:
data_path: /data

user_uid_1000:
group_gid_1000: "{{ user_uid_1000 }}"

user_uid_33: www-data
group_gid_33: "{{ user_uid_33 }}"

ca_certs_path: /etc/ssl/certs/ca-certificates.crt

docker_db_image: mariadb:10.3
docker_db_postgres_image: postgres:11
dockerfiles_path: /root/dockerfiles

## Following values will be used for the root account of every docker database
db_pass:
db_config_port: 3306

sendxmpp_jid: "{{ user_uid_1000 }}@{{ prosody_domain }}"
sendxmpp_pass:

## anarres-sec

ssh_port: 2222
admin_xmpp:

## Web and Let's Encrypt

nginx_processes: auto
web_ports_http: 80
web_ports_https: 443

web_path: /var/www

web_path_letsencrypt: "{{ web_path }}/letsencrypt"
web_path_default: "{{ web_path }}/default"


## RadioClub FTP archive

archive_ftp_domain: "ftp.{{ base_domain}}"
archive_ftp_image: acien101/alpine-apache-ftp-server:0.0.4
archive_ftp_port: 21
archive_ftp_passive_min_port: 21000
archive_ftp_passive_max_port: 21010
archive_ftp_web_port: 3444

arhive_ftp_directory:
  data: "{{ data_path }}/ftp/data"

#format `name1|password1|[folder1][|uid1] name2|password2|[folder2][|uid2]`
archive_ftp_users: "one|1234" # Changeme
